name: Validate Plugin Schema

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate PR comparison
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Validate plugin schemas
        id: schema-validation
        run: |
          echo "::group::Plugin Schema Validation"
          python scripts/validate-plugin-schema.py
          echo "::endgroup::"
      
      - name: Validate marketplace sync
        id: sync-validation
        run: |
          echo "::group::Marketplace Sync Validation"
          python scripts/validate-marketplace-sync.py
          echo "::endgroup::"
      
      - name: Validation summary
        if: always()
        run: |
          echo "### Validation Complete! 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All validation checks have been completed. Check the sections above for detailed results." >> $GITHUB_STEP_SUMMARY

