name: Validate Plugin Schema

on:
  push:
    branches: [ main, master ]
    paths:
      - 'plugins/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'plugins/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Validate plugin schemas
        run: python scripts/validate-plugin-schema.py
      
      - name: Validate marketplace sync
        run: python scripts/validate-marketplace-sync.py

